name: level_channel_platform_interface
description: A common platform interface for the level_channel plugin.
repository: https://github.com/black-golden-road/level_channel/level_channel_platform_interface
version: 0.0.1
homepage: https://github.com/black-golden-road/level_channel

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
