name: level_channel_ios
description: iOS implementation of the level_channel plugin.
repository: https://github.com/black-golden-road/level_channel/level_channel_ios
version: 0.0.1
homepage: https://github.com/black-golden-road/level_channel

publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  level_channel_platform_interface:
    path: ../level_channel_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: level_channel
    platforms:
      ios:
        pluginClass: LevelChannelIosPlugin
        dartPluginClass: LevelChannelIOS
