name: level_channel
description: A plug-in for flutter MethodChannel, converted to protocol-based rather than method-based.
version: 0.0.1
homepage: https://github.com/black-golden-road/level_channel
repository: https://github.com/black-golden-road/level_channel/level_channel

publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  level_channel_platform_interface: 
    path: ../level_channel_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.seewo.level_channel
        pluginClass: LevelChannelPlugin
      ios:
        pluginClass: LevelChannelPlugin
      web:
        pluginClass: LevelChannelWebPlugin
        fileName: src/level_channel_web.dart

