name: level_channel
description: A plug-in for flutter MethodChannel, converted to protocol-based rather than method-based.
repository: https://github.com/black-golden-road/level_channel/level_channel
version: 0.0.1
homepage: https://github.com/black-golden-road/level_channel

publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  level_channel_android: 
    path: ../level_channel_android
  level_channel_ios: 
    path: ../level_channel_ios
  level_channel_platform_interface: 
    path: ../level_channel_platform_interface
  level_channel_web: 
    path: ../level_channel_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: level_channel_android
      ios:
        default_package: level_channel_ios
      web:
        default_package: level_channel_web
   
